### ISSUE TITLE
Cuidado con los cierres

### ISSUE THREAD

**Issue by itacademyReact** [Y2KWebs/sprint2-bootstrap-itacademy#1]
Cuesta leer un poco esta parte, debería estar inline el cierre ">"
Creo que está así por el formatador automático, pero no queda del todo legible.

https://github.com/Y2KWebs/sprint2-bootstrap-itacademy/blob/40118ee66f5a8fa7ffa041064c88a0f65b766f34/N1/index.html#L65

**Comment by Y2KWebs** [comment]
Tengo que dominar todavía el Prettier para no quie no haga este tipo de cosas. Estoy en ello.
