### ISSUE TITLE
Revisar estructura de directorios

### ISSUE THREAD

**Issue by itacademyReact** [Y2KWebs/sprint2-bootstrap-itacademy#2]
No es habitual colocar la carpeta css dentro de assets.

La estructura de directorios habitual es:
https://developer.mozilla.org/es/docs/Learn/Getting_started_with_the_web/Manejando_los_archivos

https://github.com/Y2KWebs/sprint2-bootstrap-itacademy/blob/40118ee66f5a8fa7ffa041064c88a0f65b766f34/N1/assets/css/Simple-Slider.css#L1

**Comment by Y2KWebs** [comment]
De acuerdo, lo tomo en cuenta. El bootstrap studio los orgniza si por alguna razón, pero no creo que lo use mucho.
