### ISSUE TITLE
Estructura de directorios

### ISSUE THREAD

**Issue by itacademyReact** [Y2KWebs/sprint2-bootstrap-itacademy#3]
No está mal como lo has hecho, el código está organizado en directorios, pero quizá sería más conveniente poner las librerías de terceros como bootstrap y jquery en un directorio lib

https://github.com/Y2KWebs/sprint2-bootstrap-itacademy/blob/40118ee66f5a8fa7ffa041064c88a0f65b766f34/N1/assets/js/Simple-Slider.js#L1

**Comment by Y2KWebs** [comment]
Perfecto, lo tomo en cuenta para la prox
