### ISSUE TITLE
Homogeneizar contenido

### ISSUE THREAD

**Issue by itacademyReact** [Y2KWebs/sprint2-bootstrap-itacademy#4]
En este botón el texto está en nueva línea, en cambio en el resto de elementos está inline.

https://github.com/Y2KWebs/sprint2-bootstrap-itacademy/blob/40118ee66f5a8fa7ffa041064c88a0f65b766f34/N2/index.html#L151

**Comment by Y2KWebs** [comment]
Lo legro con algunos pero con otros Prettier se niega, se que hay una forma de controlarlo para que no haga este tipo de cosas, estoy en ello.
