### ISSUE TITLE
Muchos archivos en la raíz

### ISSUE THREAD

**Issue by itacademyReact** [Y2KWebs/sprint2-bootstrap-itacademy#5]
En la raíz del proyecto hay demasiados archivos. Quizá me llevaría los css a su respectiva carpeta

https://github.com/Y2KWebs/sprint2-bootstrap-itacademy/blob/40118ee66f5a8fa7ffa041064c88a0f65b766f34/N2/main.css#L1

**Comment by Y2KWebs** [comment]
Listo
